# Site settings
title: BLP
email: ""
description: >-
  Site description
url: "https://blp.com.br"
baseurl: ""


# Content settings
defaults:
  - scope:
      path: ""
    values:
      lang: pt-BR


# Build settings
permalink: pretty
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag


# SEO
lang: pt-BR